name: registry-pr-analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  analyze:
    name: generate registry summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trusted action code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: action
          persist-credentials: false
      - name: Checkout pull request contents
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: target
          persist-credentials: false
      - id: summary
        uses: ./action
        with:
          path: target
          output-directory: result
          include-examples: "true"
          command: pr-comment
      - name: Upload registry summary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: registry-pr-comment-${{ github.event.pull_request.number }}
          path: ${{ steps.summary.outputs.comment-path }}
          if-no-files-found: error
          retention-days: 7
